# Generated by Django 5.1 on 2024-08-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_email_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Укажите электронную почту",
                max_length=50,
                unique=True,
                verbose_name="Электронная почта",
            ),
        ),
    ]
